#!/usr/bin/env bash
# Pull the current TTC gateway config the same way transit.ttc.com.ge does at runtime:
# read the Firebase web config embedded in the page, register a Firebase installation,
# then fetch Remote Config. Writes ttc.properties (gitignored). Nothing is hardcoded here,
# so a key rotation on TTC's side is picked up by rerunning this.
set -euo pipefail

out="${1:-$(dirname "$0")/../ttc.properties}"
page=$(curl -fsS https://transit.ttc.com.ge/)
creds=$(printf '%s' "$page" | tr -d '\n' | grep -o '"firebaseCredentials": *{[^}]*}' | sed 's/^"firebaseCredentials": *//')
api_key=$(jq -r .apiKey <<<"$creds")
project=$(jq -r .projectId <<<"$creds")
app_id=$(jq -r .appId <<<"$creds")

fid="c$(head -c 21 /dev/urandom | base64 | tr '+/' '-_' | head -c 21)"
install=$(curl -fsS -X POST \
	-H 'Content-Type: application/json' -H "x-goog-api-key: $api_key" \
	"https://firebaseinstallations.googleapis.com/v1/projects/$project/installations" \
	-d "{\"fid\":\"$fid\",\"appId\":\"$app_id\",\"authVersion\":\"FIS_v2\",\"sdkVersion\":\"w:0.6.4\"}")
token=$(jq -r .authToken.token <<<"$install")
fid=$(jq -r .fid <<<"$install")

config=$(curl -fsS -X POST -H 'Content-Type: application/json' \
	"https://firebaseremoteconfig.googleapis.com/v1/projects/$project/namespaces/firebase:fetch?key=$api_key" \
	-d "{\"appInstanceId\":\"$fid\",\"appInstanceIdToken\":\"$token\",\"appId\":\"$app_id\",\"sdkVersion\":\"0.4.0\",\"languageCode\":\"en-US\"}")

base=$(jq -r '.entries.PIS_GATEWAY_BASE_URL // empty' <<<"$config")
key=$(jq -r '.entries.PIS_GATEWAY_KEY // empty' <<<"$config")
[ -n "$key" ] || {
	echo "Remote Config returned no PIS_GATEWAY_KEY" >&2
	exit 1
}

{
	echo "# Generated by tools/fetch-ttc-config.sh on $(date -u +%FT%TZ). Do not commit."
	echo "ttc.gatewayBaseUrl=${base:-https://transit.ttc.com.ge/pis-gateway}"
	echo "ttc.gatewayKey=$key"
	echo "ttc.firebaseApiKey=$api_key"
	echo "ttc.firebaseProjectId=$project"
	echo "ttc.firebaseAppId=$app_id"
} >"$out"
echo "Wrote $out"
