#!/usr/bin/env bash
# Fetches the Material Symbols Rounded glyphs Gza uses and writes them as vector drawables
# into :core:designsystem. Each SVG must be a single path in the 0 -960 960 960 viewBox;
# anything else fails, so an upstream format change never slips in silently.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out_dir="$root/core/designsystem/src/main/res/drawable"
base=https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded

# symbol:style:resource
icons=(
	departure_board:default:ic_nav_now
	departure_board:fill1:ic_nav_now_selected
	search:default:ic_nav_search
	map:default:ic_nav_map
	map:fill1:ic_nav_map_selected
	route:default:ic_nav_plan
	route:fill1:ic_nav_plan_selected
	settings:default:ic_nav_settings
	settings:fill1:ic_nav_settings_selected
	directions_bus:fill1:ic_mode_bus
	airport_shuttle:fill1:ic_mode_minibus
	subway:fill1:ic_mode_metro
	gondola_lift:fill1:ic_mode_cable_car
	pause_circle:fill1:ic_status_waiting
	schedule:default:ic_status_late
	calendar_clock:default:ic_status_timetable
	info:default:ic_info
	cloud_off:default:ic_offline
	directions_walk:fill1:ic_walk
)

mkdir -p "$out_dir"
for entry in "${icons[@]}"; do
	IFS=: read -r symbol style resource <<<"$entry"
	svg=$(curl -fsS "$base/$symbol/$style/24px.svg")
	if [[ $svg != *'viewBox="0 -960 960 960"'* ]]; then
		echo "$symbol/$style: unexpected viewBox" >&2
		exit 1
	fi
	paths=$(grep -o '<path ' <<<"$svg" | wc -l)
	if [[ $paths -ne 1 ]]; then
		echo "$symbol/$style: expected one path, found $paths" >&2
		exit 1
	fi
	d=$(sed -E 's/.*<path d="([^"]+)".*/\1/' <<<"$svg")
	cat >"$out_dir/$resource.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols Rounded "$symbol" ($style), Apache License 2.0. Generated by tools/fetch-icons.sh. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
        <!-- VectorPath: 24dp glyphs render fine; the paths are long because they are precise. -->
        <path
            android:fillColor="#FF000000"
            android:pathData="$d"
            tools:ignore="VectorPath" />
    </group>
</vector>
XML
	echo "$resource"
done
