package ge.hackerman.gza.buildlogic

import com.android.build.api.dsl.Lint

internal fun Lint.configureLint(checkDependencies: Boolean = false) {
    abortOnError = true
    warningsAsErrors = true
    this.checkDependencies = checkDependencies
    // xml and sarif reports are always generated by AGP 9.4, so there is nothing to switch on.
    // Version-bump checks depend on the network and the calendar, so they would turn CI red
    // without a code change. Bumps are a deliberate task.
    disable += setOf(
        "GradleDependency",
        "NewerVersionAvailable",
        "AndroidGradlePluginVersion",
        "OldTargetApi",
        // Warns about SecureRandom on Android 4.3 and older; minSdk is 26. It is a bytecode
        // check, so a source @Suppress cannot silence it.
        "TrulyRandom"
    )
}
